export enum Constants{
    error  = "error",
    accessNotAllowed = "Access not allowed",
    authenticationWhitoutRoles = "Authentication without roles",
    authenticationNotFound = "Authentication not found",
    bodyInvalid = "Body Invalid",
    customerNotFound = "Customer not found",
    customerExists  = "Customer already exists",
    flightNotFound = "Flight not found",
    flightExists = "Flight not exists",
    hotelNotFound = "Hotel not found",
    hotelExists = "Hotel already exists",
    reservationNotFound = "Reservation not found",
    reservationExists = "Reservation already exists",
    reservationCanceled = "Reservation already canceled",
    reservationConfirmed = "Reservation already confirmed",
    authNotFound = "Auth not found",
    authExists = "Auth already exists",
    credentialsNotValid = "Credentials not valid",
    accessDenied = "Access denied insufficient permissions"
}
